"""BACKTEST / IC research framework for the Stock Selection Dashboard.

A STANDING research instrument (not a one-shot script) that measures the
information content of the dashboard's production factors against forward
returns, on the canonical drift-proof total-return price panel.

Read the module docstrings in order to understand the pipeline:

  * ``panel``       -- daily TR-close matrix + monthly rebalance calendar, read
                       base-first from the canonical price-archive (READ-ONLY).
  * ``signals``     -- factor signals recomputed on the panel to the EXACT
                       product definitions (parity-tested vs the live pipeline).
  * ``membership``  -- Interface M consumer: point-in-time index-membership mask
                       (pre-inclusion-bias control). The file is built by a
                       separate agent; this reads it (or runs UNFILTERED + warns).
  * ``fundamentals``-- Interface P consumer: point-in-time fundamentals accessor
                       (as-known-at). Also built separately; consumed under
                       ``--with-fundamentals``.
  * ``forward``     -- forward total-return over 21d / 63d horizons.
  * ``metrics``     -- IC series, Newey-West t, block-bootstrap CI, quintile
                       spreads, regime splits, IC decay.
  * ``composites``  -- weighting-scheme experiments (product / variance-share /
                       literature prior) over the available factor set.
  * ``report``      -- autogenerated REPORT.md with the honest caveats up front.
  * ``run_ic``      -- CLI entry point (``python -m research.backtest.run_ic``).

Hard rules (see the task mandate):
  * READ-ONLY on price-archive / data-core / collectors. Zero writes there.
  * No yfinance fallback in research -- a missing base series is logged and
    skipped (reproducibility over coverage).
  * No new dependencies: pandas / numpy / pyyaml only (scipy used only if
    already importable, never added to requirements).
"""
